export const countries = [
  {
    name: 'Afghanistan',
    alpha2: 'AF',
    alpha3: 'AFG',
    ccTLD: 'af',
    region: 'Asia',
    subRegion: 'Southern Asia',
    languages: ['ps', 'uz', 'tk'],
  },
  {
    name: 'Åland Islands',
    alpha2: 'AX',
    alpha3: 'ALA',
    ccTLD: 'ax',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['sv'],
  },
  {
    name: 'Albania',
    alpha2: 'AL',
    alpha3: 'ALB',
    ccTLD: 'al',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['sq'],
  },
  {
    name: 'Algeria',
    alpha2: 'DZ',
    alpha3: 'DZA',
    ccTLD: 'dz',
    region: 'Africa',
    subRegion: 'Northern Africa',
    languages: ['ar'],
  },
  {
    name: 'American Samoa',
    alpha2: 'AS',
    alpha3: 'ASM',
    ccTLD: 'as',
    region: 'Oceania',
    subRegion: 'Polynesia',
    languages: ['en', 'sm'],
  },
  {
    name: 'Andorra',
    alpha2: 'AD',
    alpha3: 'AND',
    ccTLD: 'ad',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['ca'],
  },
  {
    name: 'Angola',
    alpha2: 'AO',
    alpha3: 'AGO',
    ccTLD: 'ao',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['pt'],
  },
  {
    name: 'Anguilla',
    alpha2: 'AI',
    alpha3: 'AIA',
    ccTLD: 'ai',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Antarctica',
    alpha2: 'AQ',
    alpha3: 'ATA',
    ccTLD: 'aq',
    region: '',
    subRegion: '',
    languages: [],
  },
  {
    name: 'Antigua and Barbuda',
    alpha2: 'AG',
    alpha3: 'ATG',
    ccTLD: 'ag',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Argentina',
    alpha2: 'AR',
    alpha3: 'ARG',
    ccTLD: 'ar',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es', 'gn'],
  },
  {
    name: 'Armenia',
    alpha2: 'AM',
    alpha3: 'ARM',
    ccTLD: 'am',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['hy', 'ru'],
  },
  {
    name: 'Aruba',
    alpha2: 'AW',
    alpha3: 'ABW',
    ccTLD: 'aw',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['nl', 'pa'],
  },
  {
    name: 'Assyria',
    alpha2: 'AY',
    alpha3: 'ASR',
    ccTLD: 'AY',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'Australia',
    alpha2: 'AU',
    alpha3: 'AUS',
    ccTLD: 'au',
    region: 'Oceania',
    subRegion: 'Australia and New Zealand',
    languages: ['en'],
  },
  {
    name: 'Austria',
    alpha2: 'AT',
    alpha3: 'AUT',
    ccTLD: 'at',
    region: 'Europe',
    subRegion: 'Western Europe',
    languages: ['de'],
  },
  {
    name: 'Azerbaijan',
    alpha2: 'AZ',
    alpha3: 'AZE',
    ccTLD: 'az',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['az'],
  },
  {
    name: 'Bahamas',
    alpha2: 'BS',
    alpha3: 'BHS',
    ccTLD: 'bs',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Bahrain',
    alpha2: 'BH',
    alpha3: 'BHR',
    ccTLD: 'bh',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'Bangladesh',
    alpha2: 'BD',
    alpha3: 'BGD',
    ccTLD: 'bd',
    region: 'Asia',
    subRegion: 'Southern Asia',
    languages: ['bn'],
  },
  {
    name: 'Barbados',
    alpha2: 'BB',
    alpha3: 'BRB',
    ccTLD: 'bb',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Belarus',
    alpha2: 'BY',
    alpha3: 'BLR',
    ccTLD: 'by',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['be', 'ru'],
  },
  {
    name: 'Belgium',
    alpha2: 'BE',
    alpha3: 'BEL',
    ccTLD: 'be',
    region: 'Europe',
    subRegion: 'Western Europe',
    languages: ['nl', 'fr', 'de'],
  },
  {
    name: 'Belize',
    alpha2: 'BZ',
    alpha3: 'BLZ',
    ccTLD: 'bz',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en', 'es'],
  },
  {
    name: 'Benin',
    alpha2: 'BJ',
    alpha3: 'BEN',
    ccTLD: 'bj',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr'],
  },
  {
    name: 'Bermuda',
    alpha2: 'BM',
    alpha3: 'BMU',
    ccTLD: 'bm',
    region: 'Americas',
    subRegion: 'Northern America',
    languages: ['en'],
  },
  {
    name: 'Bhutan',
    alpha2: 'BT',
    alpha3: 'BTN',
    ccTLD: 'bt',
    region: 'Asia',
    subRegion: 'Southern Asia',
    languages: ['dz'],
  },
  {
    name: 'Bolivia',
    alpha2: 'BO',
    alpha3: 'BOL',
    ccTLD: 'bo',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es', 'ay', 'qu'],
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    alpha2: 'BQ',
    alpha3: 'BES',
    ccTLD: 'bq',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['nl'],
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2: 'BA',
    alpha3: 'BIH',
    ccTLD: 'ba',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['bs', 'hr', 'sr'],
  },
  {
    name: 'Botswana',
    alpha2: 'BW',
    alpha3: 'BWA',
    ccTLD: 'bw',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en', 'tn'],
  },
  {
    name: 'Bouvet Island',
    alpha2: 'BV',
    alpha3: 'BVT',
    ccTLD: 'bv',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['no', 'nb', 'nn'],
  },
  {
    name: 'Brazil',
    alpha2: 'BR',
    alpha3: 'BRA',
    ccTLD: 'br',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['pt'],
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2: 'IO',
    alpha3: 'IOT',
    ccTLD: 'io',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en'],
  },
  {
    name: 'Brunei Darussalam',
    alpha2: 'BN',
    alpha3: 'BRN',
    ccTLD: 'bn',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['ms'],
  },
  {
    name: 'Bulgaria',
    alpha2: 'BG',
    alpha3: 'BGR',
    ccTLD: 'bg',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['bg'],
  },
  {
    name: 'Burkina Faso',
    alpha2: 'BF',
    alpha3: 'BFA',
    ccTLD: 'bf',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr', 'ff'],
  },
  {
    name: 'Burundi',
    alpha2: 'BI',
    alpha3: 'BDI',
    ccTLD: 'bi',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr', 'rn'],
  },
  {
    name: 'Cabo Verde',
    alpha2: 'CV',
    alpha3: 'CPV',
    ccTLD: 'cv',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['pt'],
  },
  {
    name: 'Cape Verde',
    alpha2: 'CV',
    alpha3: 'CPV',
    ccTLD: 'cv',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['pt'],
  },
  {
    name: 'Cambodia',
    alpha2: 'KH',
    alpha3: 'KHM',
    ccTLD: 'kh',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['km'],
  },
  {
    name: 'Cameroon',
    alpha2: 'CM',
    alpha3: 'CMR',
    ccTLD: 'cm',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en', 'fr'],
  },
  {
    name: 'Canada',
    alpha2: 'CA',
    alpha3: 'CAN',
    ccTLD: 'ca',
    region: 'Americas',
    subRegion: 'Northern America',
    languages: ['en', 'fr'],
  },
  {
    name: 'Cayman Islands',
    alpha2: 'KY',
    alpha3: 'CYM',
    ccTLD: 'ky',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Central African Republic',
    alpha2: 'CF',
    alpha3: 'CAF',
    ccTLD: 'cf',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr', 'sg'],
  },
  {
    name: 'Chad',
    alpha2: 'TD',
    alpha3: 'TCD',
    ccTLD: 'td',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr', 'ar'],
  },
  {
    name: 'Chile',
    alpha2: 'CL',
    alpha3: 'CHL',
    ccTLD: 'cl',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'China',
    alpha2: 'CN',
    alpha3: 'CHN',
    ccTLD: 'cn',
    region: 'Asia',
    subRegion: 'Eastern Asia',
    languages: ['zh'],
  },
  {
    name: 'Christmas Island',
    alpha2: 'CX',
    alpha3: 'CXR',
    ccTLD: 'cx',
    region: 'Oceania',
    subRegion: 'Australia and New Zealand',
    languages: ['en'],
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2: 'CC',
    alpha3: 'CCK',
    ccTLD: 'cc',
    region: 'Oceania',
    subRegion: 'Australia and New Zealand',
    languages: ['en'],
  },
  {
    name: 'Colombia',
    alpha2: 'CO',
    alpha3: 'COL',
    ccTLD: 'co',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Comoros',
    alpha2: 'KM',
    alpha3: 'COM',
    ccTLD: 'km',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['ar', 'fr'],
  },
  {
    name: 'Congo',
    alpha2: 'CG',
    alpha3: 'COG',
    ccTLD: 'cg',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr', 'ln'],
  },
  {
    name: 'Congo, Democratic Republic of the',
    alpha2: 'CD',
    alpha3: 'COD',
    ccTLD: 'cd',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr', 'ln', 'kg', 'sw', 'lu'],
  },
  {
    name: 'Cook Islands',
    alpha2: 'CK',
    alpha3: 'COK',
    ccTLD: 'ck',
    region: 'Oceania',
    subRegion: 'Polynesia',
    languages: ['en'],
  },
  {
    name: 'Costa Rica',
    alpha2: 'CR',
    alpha3: 'CRI',
    ccTLD: 'cr',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: "Côte d'Ivoire",
    alpha2: 'CI',
    alpha3: 'CIV',
    ccTLD: 'ci',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr'],
  },
  {
    name: 'Croatia',
    alpha2: 'HR',
    alpha3: 'HRV',
    ccTLD: 'hr',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['hr'],
  },
  {
    name: 'Cuba',
    alpha2: 'CU',
    alpha3: 'CUB',
    ccTLD: 'cu',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Curaçao',
    alpha2: 'CW',
    alpha3: 'CUW',
    ccTLD: 'cw',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['nl', 'pa', 'en'],
  },
  {
    name: 'Cyprus',
    alpha2: 'CY',
    alpha3: 'CYP',
    ccTLD: 'cy',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['el', 'tr', 'hy'],
  },
  {
    name: 'Czechia',
    alpha2: 'CZ',
    alpha3: 'CZE',
    ccTLD: 'cz',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['cs'],
  },
  {
    name: 'Czech Republic',
    alpha2: 'CZ',
    alpha3: 'CZE',
    ccTLD: 'cz',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['cs'],
  },
  {
    name: 'Denmark',
    alpha2: 'DK',
    alpha3: 'DNK',
    ccTLD: 'dk',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['da'],
  },
  {
    name: 'Djibouti',
    alpha2: 'DJ',
    alpha3: 'DJI',
    ccTLD: 'dj',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr', 'ar'],
  },
  {
    name: 'Dominica',
    alpha2: 'DM',
    alpha3: 'DMA',
    ccTLD: 'dm',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Dominican Republic',
    alpha2: 'DO',
    alpha3: 'DOM',
    ccTLD: 'do',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Ecuador',
    alpha2: 'EC',
    alpha3: 'ECU',
    ccTLD: 'ec',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Egypt',
    alpha2: 'EG',
    alpha3: 'EGY',
    ccTLD: 'eg',
    region: 'Africa',
    subRegion: 'Northern Africa',
    languages: ['ar'],
  },
  {
    name: 'El Salvador',
    alpha2: 'SV',
    alpha3: 'SLV',
    ccTLD: 'sv',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Equatorial Guinea',
    alpha2: 'GQ',
    alpha3: 'GNQ',
    ccTLD: 'gq',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['es', 'fr'],
  },
  {
    name: 'Eritrea',
    alpha2: 'ER',
    alpha3: 'ERI',
    ccTLD: 'er',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['ti', 'ar', 'en'],
  },
  {
    name: 'Estonia',
    alpha2: 'EE',
    alpha3: 'EST',
    ccTLD: 'ee',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['et'],
  },
  {
    name: 'Eswatini',
    alpha2: 'SZ',
    alpha3: 'SWZ',
    ccTLD: 'sz',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en', 'ss'],
  },
  {
    name: 'Ethiopia',
    alpha2: 'ET',
    alpha3: 'ETH',
    ccTLD: 'et',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['am'],
  },
  {
    name: 'Falkland Islands',
    alpha2: 'FK',
    alpha3: 'FLK',
    ccTLD: 'fk',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Malvinas',
    alpha2: 'FK',
    alpha3: 'FLK',
    ccTLD: 'fk',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Faroe Islands',
    alpha2: 'FO',
    alpha3: 'FRO',
    ccTLD: 'fo',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['fo'],
  },
  {
    name: 'Fiji',
    alpha2: 'FJ',
    alpha3: 'FJI',
    ccTLD: 'fj',
    region: 'Oceania',
    subRegion: 'Melanesia',
    languages: ['en', 'fj', 'hi', 'ur'],
  },
  {
    name: 'Finland',
    alpha2: 'FI',
    alpha3: 'FIN',
    ccTLD: 'fi',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['fi', 'sv'],
  },
  {
    name: 'France',
    alpha2: 'FR',
    alpha3: 'FRA',
    ccTLD: 'fr',
    region: 'Europe',
    subRegion: 'Western Europe',
    languages: ['fr'],
  },
  {
    name: 'French Guiana',
    alpha2: 'GF',
    alpha3: 'GUF',
    ccTLD: 'gf',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['fr'],
  },
  {
    name: 'French Polynesia',
    alpha2: 'PF',
    alpha3: 'PYF',
    ccTLD: 'pf',
    region: 'Oceania',
    subRegion: 'Polynesia',
    languages: ['fr'],
  },
  {
    name: 'French Southern Territories',
    alpha2: 'TF',
    alpha3: 'ATF',
    ccTLD: 'tf',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr'],
  },
  {
    name: 'Gabon',
    alpha2: 'GA',
    alpha3: 'GAB',
    ccTLD: 'ga',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr'],
  },
  {
    name: 'Gambia',
    alpha2: 'GM',
    alpha3: 'GMB',
    ccTLD: 'gm',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en'],
  },
  {
    name: 'Georgia',
    alpha2: 'GE',
    alpha3: 'GEO',
    ccTLD: 'ge',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ka'],
  },
  {
    name: 'Germany',
    alpha2: 'DE',
    alpha3: 'DEU',
    ccTLD: 'de',
    region: 'Europe',
    subRegion: 'Western Europe',
    languages: ['de'],
  },
  {
    name: 'Ghana',
    alpha2: 'GH',
    alpha3: 'GHA',
    ccTLD: 'gh',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en'],
  },
  {
    name: 'Gibraltar',
    alpha2: 'GI',
    alpha3: 'GIB',
    ccTLD: 'gi',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['en'],
  },
  {
    name: 'Greece',
    alpha2: 'GR',
    alpha3: 'GRC',
    ccTLD: 'gr',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['el'],
  },
  {
    name: 'Greenland',
    alpha2: 'GL',
    alpha3: 'GRL',
    ccTLD: 'gl',
    region: 'Americas',
    subRegion: 'Northern America',
    languages: ['kl'],
  },
  {
    name: 'Grenada',
    alpha2: 'GD',
    alpha3: 'GRD',
    ccTLD: 'gd',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Guadeloupe',
    alpha2: 'GP',
    alpha3: 'GLP',
    ccTLD: 'gp',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['fr'],
  },
  {
    name: 'Guam',
    alpha2: 'GU',
    alpha3: 'GUM',
    ccTLD: 'gu',
    region: 'Oceania',
    subRegion: 'Micronesia',
    languages: ['en', 'ch', 'es'],
  },
  {
    name: 'Guatemala',
    alpha2: 'GT',
    alpha3: 'GTM',
    ccTLD: 'gt',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Guernsey',
    alpha2: 'GG',
    alpha3: 'GGY',
    ccTLD: 'gg',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['en', 'fr'],
  },
  {
    name: 'Guinea',
    alpha2: 'GN',
    alpha3: 'GIN',
    ccTLD: 'gn',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr', 'ff'],
  },
  {
    name: 'Guinea-Bissau',
    alpha2: 'GW',
    alpha3: 'GNB',
    ccTLD: 'gw',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['pt'],
  },
  {
    name: 'Guyana',
    alpha2: 'GY',
    alpha3: 'GUY',
    ccTLD: 'gy',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Haiti',
    alpha2: 'HT',
    alpha3: 'HTI',
    ccTLD: 'ht',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['fr', 'ht'],
  },
  {
    name: 'Heard Island and McDonald Islands',
    alpha2: 'HM',
    alpha3: 'HMD',
    ccTLD: 'hm',
    region: 'Oceania',
    subRegion: 'Australia and New Zealand',
    languages: ['en'],
  },
  {
    name: 'Holy See',
    alpha2: 'VA',
    alpha3: 'VAT',
    ccTLD: 'va',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['it', 'la'],
  },
  {
    name: 'Vatican City',
    alpha2: 'VA',
    alpha3: 'VAT',
    ccTLD: 'va',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['it', 'la'],
  },
  {
    name: 'Honduras',
    alpha2: 'HN',
    alpha3: 'HND',
    ccTLD: 'hn',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Hong Kong',
    alpha2: 'HK',
    alpha3: 'HKG',
    ccTLD: 'hk',
    region: 'Asia',
    subRegion: 'Eastern Asia',
    languages: ['zh', 'en'],
  },
  {
    name: 'Hungary',
    alpha2: 'HU',
    alpha3: 'HUN',
    ccTLD: 'hu',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['hu'],
  },
  {
    name: 'Iceland',
    alpha2: 'IS',
    alpha3: 'ISL',
    ccTLD: 'is',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['is'],
  },
  {
    name: 'India',
    alpha2: 'IN',
    alpha3: 'IND',
    ccTLD: 'in',
    region: 'Asia',
    subRegion: 'Southern Asia',
    languages: ['hi', 'en'],
  },
  {
    name: 'Indonesia',
    alpha2: 'ID',
    alpha3: 'IDN',
    ccTLD: 'id',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['id'],
  },
  {
    name: 'Iran',
    alpha2: 'IR',
    alpha3: 'IRN',
    ccTLD: 'ir',
    region: 'Asia',
    subRegion: 'Southern Asia',
    languages: ['fa'],
  },
  {
    name: 'Iraq',
    alpha2: 'IQ',
    alpha3: 'IRQ',
    ccTLD: 'iq',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar', 'ku'],
  },
  {
    name: 'Ireland',
    alpha2: 'IE',
    alpha3: 'IRL',
    ccTLD: 'ie',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['ga', 'en'],
  },
  {
    name: 'Isle of Man',
    alpha2: 'IM',
    alpha3: 'IMN',
    ccTLD: 'im',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['en', 'gv'],
  },
  {
    name: 'Israel',
    alpha2: 'IL',
    alpha3: 'ISR',
    ccTLD: 'il',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['he', 'ar'],
  },
  {
    name: 'Italy',
    alpha2: 'IT',
    alpha3: 'ITA',
    ccTLD: 'it',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['it'],
  },
  {
    name: 'Jamaica',
    alpha2: 'JM',
    alpha3: 'JAM',
    ccTLD: 'jm',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Japan',
    alpha2: 'JP',
    alpha3: 'JPN',
    ccTLD: 'jp',
    region: 'Asia',
    subRegion: 'Eastern Asia',
    languages: ['ja'],
  },
  {
    name: 'Jersey',
    alpha2: 'JE',
    alpha3: 'JEY',
    ccTLD: 'je',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['en', 'fr'],
  },
  {
    name: 'Jordan',
    alpha2: 'JO',
    alpha3: 'JOR',
    ccTLD: 'jo',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'Kazakhstan',
    alpha2: 'KZ',
    alpha3: 'KAZ',
    ccTLD: 'kz',
    region: 'Asia',
    subRegion: 'Central Asia',
    languages: ['kk', 'ru'],
  },
  {
    name: 'Kenya',
    alpha2: 'KE',
    alpha3: 'KEN',
    ccTLD: 'ke',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en', 'sw'],
  },
  {
    name: 'Kiribati',
    alpha2: 'KI',
    alpha3: 'KIR',
    ccTLD: 'ki',
    region: 'Oceania',
    subRegion: 'Micronesia',
    languages: ['en'],
  },
  {
    name: "Democratic People's Republic of Korea",
    alpha2: 'KP',
    alpha3: 'PRK',
    ccTLD: 'kp',
    region: 'Asia',
    subRegion: 'Eastern Asia',
    languages: ['ko'],
  },
  {
    name: 'Korea Republic',
    alpha2: 'KR',
    alpha3: 'KOR',
    ccTLD: 'kr',
    region: 'Asia',
    subRegion: 'Eastern Asia',
    languages: ['ko'],
  },
  {
    name: 'Republic of Korea',
    alpha2: 'KR',
    alpha3: 'KOR',
    ccTLD: 'kr',
    region: 'Asia',
    subRegion: 'Eastern Asia',
    languages: ['ko'],
  },
  {
    name: 'Kuwait',
    alpha2: 'KW',
    alpha3: 'KWT',
    ccTLD: 'kw',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'Kyrgyzstan',
    alpha2: 'KG',
    alpha3: 'KGZ',
    ccTLD: 'kg',
    region: 'Asia',
    subRegion: 'Central Asia',
    languages: ['ky', 'ru'],
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2: 'LA',
    alpha3: 'LAO',
    ccTLD: 'la',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['lo'],
  },
  {
    name: 'Laos',
    alpha2: 'LA',
    alpha3: 'LAO',
    ccTLD: 'la',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['lo'],
  },
  {
    name: 'Latvia',
    alpha2: 'LV',
    alpha3: 'LVA',
    ccTLD: 'lv',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['lv'],
  },
  {
    name: 'Lebanon',
    alpha2: 'LB',
    alpha3: 'LBN',
    ccTLD: 'lb',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar', 'fr'],
  },
  {
    name: 'Lesotho',
    alpha2: 'LS',
    alpha3: 'LSO',
    ccTLD: 'ls',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en', 'st'],
  },
  {
    name: 'Liberia',
    alpha2: 'LR',
    alpha3: 'LBR',
    ccTLD: 'lr',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en'],
  },
  {
    name: 'Libya',
    alpha2: 'LY',
    alpha3: 'LBY',
    ccTLD: 'ly',
    region: 'Africa',
    subRegion: 'Northern Africa',
    languages: ['ar'],
  },
  {
    name: 'Liechtenstein',
    alpha2: 'LI',
    alpha3: 'LIE',
    ccTLD: 'li',
    region: 'Europe',
    subRegion: 'Western Europe',
    languages: ['de'],
  },
  {
    name: 'Lithuania',
    alpha2: 'LT',
    alpha3: 'LTU',
    ccTLD: 'lt',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['lt'],
  },
  {
    name: 'Luxembourg',
    alpha2: 'LU',
    alpha3: 'LUX',
    ccTLD: 'lu',
    region: 'Europe',
    subRegion: 'Western Europe',
    languages: ['fr', 'de', 'lb'],
  },
  {
    name: 'Macao',
    alpha2: 'MO',
    alpha3: 'MAC',
    ccTLD: 'mo',
    region: 'Asia',
    subRegion: 'Eastern Asia',
    languages: ['zh', 'pt'],
  },
  {
    name: 'Madagascar',
    alpha2: 'MG',
    alpha3: 'MDG',
    ccTLD: 'mg',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr', 'mg'],
  },
  {
    name: 'Malawi',
    alpha2: 'MW',
    alpha3: 'MWI',
    ccTLD: 'mw',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en', 'ny'],
  },
  {
    name: 'Malaysia',
    alpha2: 'MY',
    alpha3: 'MYS',
    ccTLD: 'my',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['ms'],
  },
  {
    name: 'Maldives',
    alpha2: 'MV',
    alpha3: 'MDV',
    ccTLD: 'mv',
    region: 'Asia',
    subRegion: 'Southern Asia',
    languages: ['dv'],
  },
  {
    name: 'Mali',
    alpha2: 'ML',
    alpha3: 'MLI',
    ccTLD: 'ml',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr'],
  },
  {
    name: 'Malta',
    alpha2: 'MT',
    alpha3: 'MLT',
    ccTLD: 'mt',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['mt', 'en'],
  },
  {
    name: 'Marshall Islands',
    alpha2: 'MH',
    alpha3: 'MHL',
    ccTLD: 'mh',
    region: 'Oceania',
    subRegion: 'Micronesia',
    languages: ['en', 'mh'],
  },
  {
    name: 'Martinique',
    alpha2: 'MQ',
    alpha3: 'MTQ',
    ccTLD: 'mq',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['fr'],
  },
  {
    name: 'Mauritania',
    alpha2: 'MR',
    alpha3: 'MRT',
    ccTLD: 'mr',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['ar'],
  },
  {
    name: 'Mauritius',
    alpha2: 'MU',
    alpha3: 'MUS',
    ccTLD: 'mu',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en'],
  },
  {
    name: 'Mayotte',
    alpha2: 'YT',
    alpha3: 'MYT',
    ccTLD: 'yt',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr'],
  },
  {
    name: 'Mexico',
    alpha2: 'MX',
    alpha3: 'MEX',
    ccTLD: 'mx',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Micronesia',
    alpha2: 'FM',
    alpha3: 'FSM',
    ccTLD: 'fm',
    region: 'Oceania',
    subRegion: 'Micronesia',
    languages: ['en'],
  },
  {
    name: 'Moldova',
    alpha2: 'MD',
    alpha3: 'MDA',
    ccTLD: 'md',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['ro'],
  },
  {
    name: 'Monaco',
    alpha2: 'MC',
    alpha3: 'MCO',
    ccTLD: 'mc',
    region: 'Europe',
    subRegion: 'Western Europe',
    languages: ['fr'],
  },
  {
    name: 'Mongolia',
    alpha2: 'MN',
    alpha3: 'MNG',
    ccTLD: 'mn',
    region: 'Asia',
    subRegion: 'Eastern Asia',
    languages: ['mn'],
  },
  {
    name: 'Montenegro',
    alpha2: 'ME',
    alpha3: 'MNE',
    ccTLD: 'me',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['sr', 'bs', 'sq', 'hr'],
  },
  {
    name: 'Montserrat',
    alpha2: 'MS',
    alpha3: 'MSR',
    ccTLD: 'ms',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Morocco',
    alpha2: 'MA',
    alpha3: 'MAR',
    ccTLD: 'ma',
    region: 'Africa',
    subRegion: 'Northern Africa',
    languages: ['ar'],
  },
  {
    name: 'Mozambique',
    alpha2: 'MZ',
    alpha3: 'MOZ',
    ccTLD: 'mz',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['pt'],
  },
  {
    name: 'Myanmar',
    alpha2: 'MM',
    alpha3: 'MMR',
    ccTLD: 'mm',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['my'],
  },
  {
    name: 'Namibia',
    alpha2: 'NA',
    alpha3: 'NAM',
    ccTLD: 'na',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en', 'af'],
  },
  {
    name: 'Nauru',
    alpha2: 'NR',
    alpha3: 'NRU',
    ccTLD: 'nr',
    region: 'Oceania',
    subRegion: 'Micronesia',
    languages: ['en', 'na'],
  },
  {
    name: 'Nepal',
    alpha2: 'NP',
    alpha3: 'NPL',
    ccTLD: 'np',
    region: 'Asia',
    subRegion: 'Southern Asia',
    languages: ['ne'],
  },
  {
    name: 'Netherlands',
    alpha2: 'NL',
    alpha3: 'NLD',
    ccTLD: 'nl',
    region: 'Europe',
    subRegion: 'Western Europe',
    languages: ['nl'],
  },
  {
    name: 'New Caledonia',
    alpha2: 'NC',
    alpha3: 'NCL',
    ccTLD: 'nc',
    region: 'Oceania',
    subRegion: 'Melanesia',
    languages: ['fr'],
  },
  {
    name: 'New Zealand',
    alpha2: 'NZ',
    alpha3: 'NZL',
    ccTLD: 'nz',
    region: 'Oceania',
    subRegion: 'Australia and New Zealand',
    languages: ['en', 'mi'],
  },
  {
    name: 'Nicaragua',
    alpha2: 'NI',
    alpha3: 'NIC',
    ccTLD: 'ni',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Niger',
    alpha2: 'NE',
    alpha3: 'NER',
    ccTLD: 'ne',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr'],
  },
  {
    name: 'Nigeria',
    alpha2: 'NG',
    alpha3: 'NGA',
    ccTLD: 'ng',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en'],
  },
  {
    name: 'Niue',
    alpha2: 'NU',
    alpha3: 'NIU',
    ccTLD: 'nu',
    region: 'Oceania',
    subRegion: 'Polynesia',
    languages: ['en'],
  },
  {
    name: 'Norfolk Island',
    alpha2: 'NF',
    alpha3: 'NFK',
    ccTLD: 'nf',
    region: 'Oceania',
    subRegion: 'Australia and New Zealand',
    languages: ['en'],
  },
  {
    name: 'North Macedonia',
    alpha2: 'MK',
    alpha3: 'MKD',
    ccTLD: 'mk',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['mk'],
  },
  {
    name: 'Northern Mariana Islands',
    alpha2: 'MP',
    alpha3: 'MNP',
    ccTLD: 'mp',
    region: 'Oceania',
    subRegion: 'Micronesia',
    languages: ['en', 'ch'],
  },
  {
    name: 'Norway',
    alpha2: 'NO',
    alpha3: 'NOR',
    ccTLD: 'no',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['no', 'nb', 'nn'],
  },
  {
    name: 'Oman',
    alpha2: 'OM',
    alpha3: 'OMN',
    ccTLD: 'om',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'Pakistan',
    alpha2: 'PK',
    alpha3: 'PAK',
    ccTLD: 'pk',
    region: 'Asia',
    subRegion: 'Southern Asia',
    languages: ['en', 'ur'],
  },
  {
    name: 'Palau',
    alpha2: 'PW',
    alpha3: 'PLW',
    ccTLD: 'pw',
    region: 'Oceania',
    subRegion: 'Micronesia',
    languages: ['en'],
  },
  {
    name: 'Palestine',
    alpha2: 'PS',
    alpha3: 'PSE',
    ccTLD: 'ps',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'State of Palestine',
    alpha2: 'PS',
    alpha3: 'PSE',
    ccTLD: 'ps',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'Panama',
    alpha2: 'PA',
    alpha3: 'PAN',
    ccTLD: 'pa',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Papua New Guinea',
    alpha2: 'PG',
    alpha3: 'PNG',
    ccTLD: 'pg',
    region: 'Oceania',
    subRegion: 'Melanesia',
    languages: ['en'],
  },
  {
    name: 'Paraguay',
    alpha2: 'PY',
    alpha3: 'PRY',
    ccTLD: 'py',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es', 'gn'],
  },
  {
    name: 'Peru',
    alpha2: 'PE',
    alpha3: 'PER',
    ccTLD: 'pe',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Philippines',
    alpha2: 'PH',
    alpha3: 'PHL',
    ccTLD: 'ph',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['en'],
  },
  {
    name: 'Pitcairn',
    alpha2: 'PN',
    alpha3: 'PCN',
    ccTLD: 'pn',
    region: 'Oceania',
    subRegion: 'Polynesia',
    languages: ['en'],
  },
  {
    name: 'Poland',
    alpha2: 'PL',
    alpha3: 'POL',
    ccTLD: 'pl',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['pl'],
  },
  {
    name: 'Portugal',
    alpha2: 'PT',
    alpha3: 'PRT',
    ccTLD: 'pt',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['pt'],
  },
  {
    name: 'Puerto Rico',
    alpha2: 'PR',
    alpha3: 'PRI',
    ccTLD: 'pr',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es', 'en'],
  },
  {
    name: 'Qatar',
    alpha2: 'QA',
    alpha3: 'QAT',
    ccTLD: 'qa',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'Réunion',
    alpha2: 'RE',
    alpha3: 'REU',
    ccTLD: 're',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr'],
  },
  {
    name: 'Romania',
    alpha2: 'RO',
    alpha3: 'ROU',
    ccTLD: 'ro',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['ro'],
  },
  {
    name: 'Russian Federation',
    alpha2: 'RU',
    alpha3: 'RUS',
    ccTLD: 'ru',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['ru'],
  },
  {
    name: 'Russia',
    alpha2: 'RU',
    alpha3: 'RUS',
    ccTLD: 'ru',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['ru'],
  },
  {
    name: 'Rwanda',
    alpha2: 'RW',
    alpha3: 'RWA',
    ccTLD: 'rw',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['rw', 'en', 'fr'],
  },
  {
    name: 'Saint Barthélemy',
    alpha2: 'BL',
    alpha3: 'BLM',
    ccTLD: 'bl',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['fr'],
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    alpha2: 'SH',
    alpha3: 'SHN',
    ccTLD: 'sh',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en'],
  },
  {
    name: 'Saint Helena',
    alpha2: 'SH',
    alpha3: 'SHN',
    ccTLD: 'sh',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en'],
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2: 'KN',
    alpha3: 'KNA',
    ccTLD: 'kn',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Saint Lucia',
    alpha2: 'LC',
    alpha3: 'LCA',
    ccTLD: 'lc',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Saint Martin (French part)',
    alpha2: 'MF',
    alpha3: 'MAF',
    ccTLD: 'mf',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en', 'fr', 'nl'],
  },
  {
    name: 'Saint Martin',
    alpha2: 'MF',
    alpha3: 'MAF',
    ccTLD: 'mf',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en', 'fr', 'nl'],
  },
  {
    name: 'Saint Pierre and Miquelon',
    alpha2: 'PM',
    alpha3: 'SPM',
    ccTLD: 'pm',
    region: 'Americas',
    subRegion: 'Northern America',
    languages: ['fr'],
  },
  {
    name: 'Saint Vincent and the Grenadines',
    alpha2: 'VC',
    alpha3: 'VCT',
    ccTLD: 'vc',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Samoa',
    alpha2: 'WS',
    alpha3: 'WSM',
    ccTLD: 'ws',
    region: 'Oceania',
    subRegion: 'Polynesia',
    languages: ['sm', 'en'],
  },
  {
    name: 'San Marino',
    alpha2: 'SM',
    alpha3: 'SMR',
    ccTLD: 'sm',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['it'],
  },
  {
    name: 'Sao Tome and Principe',
    alpha2: 'ST',
    alpha3: 'STP',
    ccTLD: 'st',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['pt'],
  },
  {
    name: 'Saudi Arabia',
    alpha2: 'SA',
    alpha3: 'SAU',
    ccTLD: 'sa',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'Senegal',
    alpha2: 'SN',
    alpha3: 'SEN',
    ccTLD: 'sn',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr'],
  },
  {
    name: 'Serbia',
    alpha2: 'RS',
    alpha3: 'SRB',
    ccTLD: 'rs',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['sr'],
  },
  {
    name: 'Seychelles',
    alpha2: 'SC',
    alpha3: 'SYC',
    ccTLD: 'sc',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr', 'en'],
  },
  {
    name: 'Sierra Leone',
    alpha2: 'SL',
    alpha3: 'SLE',
    ccTLD: 'sl',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en'],
  },
  {
    name: 'Singapore',
    alpha2: 'SG',
    alpha3: 'SGP',
    ccTLD: 'sg',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['en', 'ms', 'ta', 'zh'],
  },
  {
    name: 'Sint Maarten (Dutch part)',
    alpha2: 'SX',
    alpha3: 'SXM',
    ccTLD: 'sx',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['nl', 'en'],
  },
  {
    name: 'Slovakia',
    alpha2: 'SK',
    alpha3: 'SVK',
    ccTLD: 'sk',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['sk'],
  },
  {
    name: 'Slovenia',
    alpha2: 'SI',
    alpha3: 'SVN',
    ccTLD: 'si',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['sl'],
  },
  {
    name: 'Solomon Islands',
    alpha2: 'SB',
    alpha3: 'SLB',
    ccTLD: 'sb',
    region: 'Oceania',
    subRegion: 'Melanesia',
    languages: ['en'],
  },
  {
    name: 'Somalia',
    alpha2: 'SO',
    alpha3: 'SOM',
    ccTLD: 'so',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['so', 'ar'],
  },
  {
    name: 'South Africa',
    alpha2: 'ZA',
    alpha3: 'ZAF',
    ccTLD: 'za',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['af', 'en', 'nr', 'st', 'ss', 'tn', 'ts', 've', 'xh', 'zu'],
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    alpha2: 'GS',
    alpha3: 'SGS',
    ccTLD: 'gs',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'South Sudan',
    alpha2: 'SS',
    alpha3: 'SSD',
    ccTLD: 'ss',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en'],
  },
  {
    name: 'Spain',
    alpha2: 'ES',
    alpha3: 'ESP',
    ccTLD: 'es',
    region: 'Europe',
    subRegion: 'Southern Europe',
    languages: ['es', 'eu', 'ca', 'gl', 'oc'],
  },
  {
    name: 'Sri Lanka',
    alpha2: 'LK',
    alpha3: 'LKA',
    ccTLD: 'lk',
    region: 'Asia',
    subRegion: 'Southern Asia',
    languages: ['si', 'ta'],
  },
  {
    name: 'Sudan',
    alpha2: 'SD',
    alpha3: 'SDN',
    ccTLD: 'sd',
    region: 'Africa',
    subRegion: 'Northern Africa',
    languages: ['ar', 'en'],
  },
  {
    name: 'Suriname',
    alpha2: 'SR',
    alpha3: 'SUR',
    ccTLD: 'sr',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['nl'],
  },
  {
    name: 'Svalbard and Jan Mayen',
    alpha2: 'SJ',
    alpha3: 'SJM',
    ccTLD: 'sj',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['no'],
  },
  {
    name: 'Sweden',
    alpha2: 'SE',
    alpha3: 'SWE',
    ccTLD: 'se',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['sv'],
  },
  {
    name: 'Switzerland',
    alpha2: 'CH',
    alpha3: 'CHE',
    ccTLD: 'ch',
    region: 'Europe',
    subRegion: 'Western Europe',
    languages: ['de', 'fr', 'it'],
  },
  {
    name: 'Syrian Arab Republic',
    alpha2: 'SY',
    alpha3: 'SYR',
    ccTLD: 'sy',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'Taiwan',
    alpha2: 'TW',
    alpha3: 'TWN',
    ccTLD: 'tw',
    region: 'Asia',
    subRegion: 'Eastern Asia',
    languages: ['zh'],
  },
  {
    name: 'Tajikistan',
    alpha2: 'TJ',
    alpha3: 'TJK',
    ccTLD: 'tj',
    region: 'Asia',
    subRegion: 'Central Asia',
    languages: ['tg', 'ru'],
  },
  {
    name: 'Tanzania',
    alpha2: 'TZ',
    alpha3: 'TZA',
    ccTLD: 'tz',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['sw', 'en'],
  },
  {
    name: 'Thailand',
    alpha2: 'TH',
    alpha3: 'THA',
    ccTLD: 'th',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['th'],
  },
  {
    name: 'Timor-Leste',
    alpha2: 'TL',
    alpha3: 'TLS',
    ccTLD: 'tl',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['pt'],
  },
  {
    name: 'Togo',
    alpha2: 'TG',
    alpha3: 'TGO',
    ccTLD: 'tg',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['fr'],
  },
  {
    name: 'Tokelau',
    alpha2: 'TK',
    alpha3: 'TKL',
    ccTLD: 'tk',
    region: 'Oceania',
    subRegion: 'Polynesia',
    languages: ['en'],
  },
  {
    name: 'Tonga',
    alpha2: 'TO',
    alpha3: 'TON',
    ccTLD: 'to',
    region: 'Oceania',
    subRegion: 'Polynesia',
    languages: ['en', 'to'],
  },
  {
    name: 'Trinidad and Tobago',
    alpha2: 'TT',
    alpha3: 'TTO',
    ccTLD: 'tt',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Trinidad',
    alpha2: 'TT',
    alpha3: 'TTO',
    ccTLD: 'tt',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Tunisia',
    alpha2: 'TN',
    alpha3: 'TUN',
    ccTLD: 'tn',
    region: 'Africa',
    subRegion: 'Northern Africa',
    languages: ['ar'],
  },
  {
    name: 'Turkey',
    alpha2: 'TR',
    alpha3: 'TUR',
    ccTLD: 'tr',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['tr'],
  },
  {
    name: 'Turkmenistan',
    alpha2: 'TM',
    alpha3: 'TKM',
    ccTLD: 'tm',
    region: 'Asia',
    subRegion: 'Central Asia',
    languages: ['tk', 'ru'],
  },
  {
    name: 'Turks and Caicos Islands',
    alpha2: 'TC',
    alpha3: 'TCA',
    ccTLD: 'tc',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Tuvalu',
    alpha2: 'TV',
    alpha3: 'TUV',
    ccTLD: 'tv',
    region: 'Oceania',
    subRegion: 'Polynesia',
    languages: ['en'],
  },
  {
    name: 'Uganda',
    alpha2: 'UG',
    alpha3: 'UGA',
    ccTLD: 'ug',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en', 'sw'],
  },
  {
    name: 'Ukraine',
    alpha2: 'UA',
    alpha3: 'UKR',
    ccTLD: 'ua',
    region: 'Europe',
    subRegion: 'Eastern Europe',
    languages: ['uk'],
  },
  {
    name: 'United Arab Emirates',
    alpha2: 'AE',
    alpha3: 'ARE',
    ccTLD: 'ae',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    alpha2: 'GB',
    alpha3: 'GBR',
    ccTLD: 'uk',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['en'],
  },
  {
    name: 'England',
    alpha2: 'GB-ENG',
    alpha3: 'GBR',
    ccTLD: 'uk',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['en'],
  },
  {
    name: 'Northern Ireland',
    alpha2: 'GB-NIR',
    alpha3: 'GBR',
    ccTLD: 'uk',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['en'],
  },
  {
    name: 'Scotland',
    alpha2: 'GB-SCT',
    alpha3: 'GBR',
    ccTLD: 'uk',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['en'],
  },
  {
    name: 'Wales',
    alpha2: 'GB-WLS',
    alpha3: 'GBR',
    ccTLD: 'uk',
    region: 'Europe',
    subRegion: 'Northern Europe',
    languages: ['en'],
  },
  {
    name: 'United States of America',
    alpha2: 'US',
    alpha3: 'USA',
    ccTLD: 'us',
    region: 'Americas',
    subRegion: 'Northern America',
    languages: ['en'],
  },
  {
    name: 'United States Minor Outlying Islands',
    alpha2: 'UM',
    alpha3: 'UMI',
    ccTLD: 'us',
    region: 'Oceania',
    subRegion: 'Micronesia',
    languages: ['en'],
  },
  {
    name: 'Uruguay',
    alpha2: 'UY',
    alpha3: 'URY',
    ccTLD: 'uy',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Uzbekistan',
    alpha2: 'UZ',
    alpha3: 'UZB',
    ccTLD: 'uz',
    region: 'Asia',
    subRegion: 'Central Asia',
    languages: ['uz', 'ru'],
  },
  {
    name: 'Vanuatu',
    alpha2: 'VU',
    alpha3: 'VUT',
    ccTLD: 'vu',
    region: 'Oceania',
    subRegion: 'Melanesia',
    languages: ['bi', 'en', 'fr'],
  },
  {
    name: 'Venezuela',
    alpha2: 'VE',
    alpha3: 'VEN',
    ccTLD: 've',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['es'],
  },
  {
    name: 'Vietnam',
    alpha2: 'VN',
    alpha3: 'VNM',
    ccTLD: 'vn',
    region: 'Asia',
    subRegion: 'South-eastern Asia',
    languages: ['vi'],
  },
  {
    name: 'Virgin Islands (British)',
    alpha2: 'VG',
    alpha3: 'VGB',
    ccTLD: 'vg',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'British Virgin Islands',
    alpha2: 'VG',
    alpha3: 'VGB',
    ccTLD: 'vg',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Virgin Islands (U.S.)',
    alpha2: 'VI',
    alpha3: 'VIR',
    ccTLD: 'vi',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'U.S. Virgin Islands',
    alpha2: 'VI',
    alpha3: 'VIR',
    ccTLD: 'vi',
    region: 'Americas',
    subRegion: 'Latin America and the Caribbean',
    languages: ['en'],
  },
  {
    name: 'Wallis and Futuna',
    alpha2: 'WF',
    alpha3: 'WLF',
    ccTLD: 'wf',
    region: 'Oceania',
    subRegion: 'Polynesia',
    languages: ['fr'],
  },
  {
    name: 'Western Sahara',
    alpha2: 'EH',
    alpha3: 'ESH',
    ccTLD: 'eh',
    region: 'Africa',
    subRegion: 'Northern Africa',
    languages: ['es'],
  },
  {
    name: 'Yemen',
    alpha2: 'YE',
    alpha3: 'YEM',
    ccTLD: 'ye',
    region: 'Asia',
    subRegion: 'Western Asia',
    languages: ['ar'],
  },
  {
    name: 'Zambia',
    alpha2: 'ZM',
    alpha3: 'ZMB',
    ccTLD: 'zm',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en'],
  },
  {
    name: 'Zimbabwe',
    alpha2: 'ZW',
    alpha3: 'ZWE',
    ccTLD: 'zw',
    region: 'Africa',
    subRegion: 'Sub-Saharan Africa',
    languages: ['en', 'sn', 'nd'],
  },
]
